spring:
  application:
    name: eureka
    server:
      port: 8070
  management:
    tracing:
      sampling:
        probability: 1.0
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    metrics:
      export:
        prometheus:
          enabled: true
    eureka:
      instance:
        hostname: localhost
      client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/