apiVersion: v1
kind: Service
metadata:
  name: orderapp-svc
spec:
  type: NodePort
  selector:
    app: orderapp
  ports:
  - port: 8080 #port that we want to expose for pod
    targetPort: 8081 #port inside container
    nodePort: 30001
